data_aktivasi_voucher = [
    # telkomsel
    {
        "kode": "UVTJBR0-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 4GB / 1 hari",
        "desc": "prasticareload.com",
        "harga": 7325,
        "hargaJual": 10000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVTJBR0A-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 6GB / 2 hari",
        "desc": "prasticareload.com",
        "harga": 10445,
        "hargaJual": 13000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVTJBR3B-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 7GB / 7 hari",
        "desc": "prasticareload.com",
        "harga": 22925,
        "hargaJual": 26000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    
    # axis
    {
        "kode": "UVAM1C-PR",
        "provider": "axis",
        "jenisPaket": "UNLOCK VOC AXIS DATA MINI",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Akt. Voucher AIGO 3GB + Kuota Di Kotamu / 3 hari",
        "desc": "prasticareload.com",
        "harga": 9375,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVAM6GB3-PR",
        "provider": "axis",
        "jenisPaket": "UNLOCK VOC AXIS DATA MINI",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Akt. Voucher AIGO 8.5GB + Kuota Di Kotamu / 3 hari",
        "desc": "prasticareload.com",
        "harga": 12925,
        "hargaJual": 15000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    
    # xl
    {
        "kode": "UVXFM4G3-PR",
        "provider": "xl",
        "jenisPaket": "UNLOCK VOC XL FLEX MINI",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Vocer Flex Mini 4GB / 3 hari",
        "desc": "prasticareload.com",
        "harga": 11905,
        "hargaJual": 15000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    # indosat
    {
        "kode": "UVIJBR5-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 6GB / 2 hari",
        "desc": "prasticareload.com",
        "harga": 9525,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVIJBR5A-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 6GB / 3 hari",
        "desc": "prasticareload.com",
        "harga": 12825,
        "hargaJual": 15000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVIJBR2-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 4GB / 5 hari",
        "desc": "prasticareload.com",
        "harga": 13075,
        "hargaJual": 16000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVIJBR3B-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 6GB / 5 hari",
        "desc": "prasticareload.com",
        "harga": 14575,
        "hargaJual": 17000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVIJBR7-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 9GB / 7 hari",
        "desc": "prasticareload.com",
        "harga": 22725,
        "hargaJual": 25000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVIJBR15-PR",
        "provider": "indosat",
        "jenisPaket": "UNLOCK VOC ISAT DATA SACHET",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Act. Voucher 17GB / 7 hari",
        "desc": "prasticareload.com",
        "harga": 28025,
        "hargaJual": 31000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
]