data_aktivasi_voucher = [
    # telkomsel
    {
        "kode": "UVTJBR0-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 4GB / 1 hari",
        "desc": "prasticareload.com",
        "harga": 7325,
        "hargaJual": 10000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVTJBR0A-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 6GB / 2 hari",
        "desc": "prasticareload.com",
        "harga": 10445,
        "hargaJual": 13000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVTJBR3B-PR",
        "provider": "telkomsel",
        "jenisPaket": "UNLOCK VOC TSEL JABAR",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Aktivasi Voucher 7GB / 7 hari",
        "desc": "prasticareload.com",
        "harga": 22925,
        "hargaJual": 26000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    
    # axis
    {
        "kode": "UVAM1C-PR",
        "provider": "axis",
        "jenisPaket": "UNLOCK VOC AXIS DATA MINI",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Akt. Voucher AIGO 3GB + Kuota Di Kotamu / 3 hari",
        "desc": "prasticareload.com",
        "harga": 9375,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "UVAM6GB3-PR",
        "provider": "axis",
        "jenisPaket": "UNLOCK VOC AXIS DATA MINI",
        "kategori": "aktivasi voucher internet",
        "produk": "Inject Voucher - Akt. Voucher AIGO 8.5GB + Kuota Di Kotamu / 3 hari",
        "desc": "prasticareload.com",
        "harga": 12925,
        "hargaJual": 15000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
]