data_voucher_internet = [
    # telkomsel
    {
        "kode": "TVJBR5G2-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 6GB / 2 Hari",
        "desc": "prasticareload.com",
        "harga": 10925,
        "hargaJual": 13000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "TVJBR1C-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 5GB / 3 Hari",
        "desc": "prasticareload.com",
        "harga": 13525,
        "hargaJual": 16000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "TVJBR1B-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 5GB / 7 Hari",
        "desc": "prasticareload.com",
        "harga": 19875,
        "hargaJual": 22000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    # axis
    {
        "kode": "VAM300-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 5GB Reg + Kuota di Kotamu / 1 Hari",
        "desc": "prasticareload.com",
        "harga": 6985,
        "hargaJual": 8000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "VAM1-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 3GB Reg + Kuota di Kotamu / 3 Hari",
        "desc": "prasticareload.com",
        "harga": 9975,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "VAM2-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Voucher Kuota 5GB Reg + Kuota di Kotamu / 3 Hari",
        "desc": "prasticareload.com",
        "harga": 11375,
        "hargaJual": 14000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    }
]