data_voucher_internet = [
    {
        "kode": "VAM1-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 3GB Reg + Kuota di Kotamu / 3 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 9975,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM2-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 5GB Reg + Kuota di Kotamu / 3 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 11375,
        "hargaJual": 13000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM3-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 12.5GB Reg + Kuota di Kotamu / 3 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 16225,
        "hargaJual": 18000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM1C-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 3.5GB Reg + Lokal Non Jawa Bali Nusra / 5 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 13075,
        "hargaJual": 15000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM2A-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 5GB Reg + Kuota di Kotamu / 5 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 14825,
        "hargaJual": 17000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM3A-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 16GB Reg + Kuota di Kotamu / 5 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 22975,
        "hargaJual": 26000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM1D-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 3GB Reg + Kuota di Kotamu / 7 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 13800,
        "hargaJual": 16000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAMS1-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 10GB Reg + Kuota di Kotamu / 7 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 23020,
        "hargaJual": 26000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAMS2-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 17GB Reg + Kuota di Kotamu / 7 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 28625,
        "hargaJual": 32000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAM5G14-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 5GB Reg + Kuota di Kotamu / 14 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 22125,
        "hargaJual": 25000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VAMS1A-PR",
        "provider": "axis",
        "jenisPaket": "VOC AXIS DATA MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 8GB Reg + Kuota di Kotamu / 14 Hari",
        "desc": "VOC AXIS DATA MINI",
        "harga": 27425,
        "hargaJual": 30000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "TVJBR5G1-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 1GB Reg + 3GB Lokal Jabar / 1 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 7950,
        "hargaJual": 10000,
        "order": "ORDER",
        "aktif": True,
        "link": "",
    },
    {
        "kode": "TVJBR5G2-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 3GB Reg + 3GB Lokal Jabar / 2 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 10975,
        "hargaJual": 13000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "TVJBR1C-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 2GB Reg + 3GB Lokal Jabar / 3 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 13525,
        "hargaJual": 16000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "TVJBR2B-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 1.5GB Reg + 4GB Lokal Jabar / 5 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 23275,
        "hargaJual": 26000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "TVJBR1B-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 2GB Reg + 3GB Lokal Jabar / 7 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 20250,
        "hargaJual": 22000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "TVJBR7G7-PR",
        "provider": "telkomsel",
        "jenisPaket": "VOC TELKOMSEL DATA JAWA BARAT",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - 3GB Reg + 4GB Lokal Jabar / 7 Hari",
        "desc": "VOC TELKOMSEL DATA JAWA BARAT",
        "harga": 23525,
        "hargaJual": 27000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM3G1H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 3GB / 1 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 7075,
        "hargaJual": 9000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM6G2H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 6GB / 2 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 9925,
        "hargaJual": 12000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM3G3H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 3.5GB / 3 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 12495,
        "hargaJual": 14000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM6G3H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 6GB / 3 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 14250,
        "hargaJual": 16000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM4G7H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 4GB / 7 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 15535,
        "hargaJual": 18000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM6G7H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 6GB / 7 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 18855,
        "hargaJual": 21000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM10G7H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 10GB / 7 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 23755,
        "hargaJual": 27000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM3G14-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 3GB / 14 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 19325,
        "hargaJual": 21000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
    {
        "kode": "VXDFM8G14H-PR",
        "provider": "xl",
        "jenisPaket": "VOC XL FLEX MINI",
        "kategori": "voucher internet",
        "produk": "Voucher Internet - Flex Mini 8GB / 14 Hari",
        "desc": "VOC XL FLEX MINI",
        "harga": 28280,
        "hargaJual": 31000,
        "order": "ORDER",
        "aktif": False,
        "link": "",
    },
]
